### ISSUE TITLE
Use this as default video player for ownCloud 9.0?

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/videojs-sublime#23]
@karlitschek @DeepDiver1975 @Instagit as mentioned in the past, we should move to this video player for ownCloud 9. It works better, is responsive, and looks much nicer. What is left to do, if anything except moving repositories?

**Comment by karlitschek** [comment]
I have to check the license first. let's talk next week.

**Comment by jancborchardt** [comment]
Sure. Was just worried regarding feature freeze. For reference:

- video.js is Apache 2: https://github.com/videojs/video.js/blob/master/LICENSE
- the theme is MIT: https://github.com/cabin/videojs-sublime-skin/blob/master/LICENSE
- this app is AGPL: https://github.com/Instagit/videojs-sublime#license

**Comment by karlitschek** [comment]
We would need a contributor agreement for the contributors of this app or alternatively a relicensing to MIT or Apache.

**Comment by karlitschek** [comment]
If we have that then we can make the move.

**Comment by Instagit** [comment]
I'd be fine with relicensing to MIT. The reason I made it AGPL is that the app is originally based on [this app](https://apps.owncloud.com/content/show.php/Video+Js?content=159670), which is AGPL, too.

Maybe you have better luck contacting the author. I tried several months ago to no avail.

The only file in question is [viewer.js](https://github.com/Instagit/videojs-sublime/blob/master/js/viewer.js), which had most of its code changed by now. If we can't contact the original author, would it be an option to rewrite the file?

**Comment by jancborchardt** [comment]
Looking at the viewer.js file you linked, the really important lines were rewritten by you since the »initial commit« which I assume was the original other code.

What do you think @karlitschek @schiesbn?

**Comment by karlitschek** [comment]
If the important lines are rewritten then this a relicensing is possible. @Instagit Do you want to relicense the app as MIT? You would have to change all the license header to MIT then please. We can then switch to your app for 9.0
Are you O.K. with moving the app to the owncloud github organisation? You would still have full access and control obviously.

**Comment by Instagit** [comment]
The file was straightforward code without much programming logic in it to begin with and [the lines that remain](https://github.com/Instagit/videojs-sublime/compare/1c800ca9c49a2ae950ec267d6463b4121de1709d...c173036333f3f53ee2df2a0c0fa3a8d9ec98f9d3) are very trivial code, so I would go ahead and relicense this app. I'll make the changes later today.

**Comment by karlitschek** [comment]
perfect. thanks. @deepdiver1975 can you help with moving the repo into the ownCloud organisation while keeping the repository name the same?

**Comment by DeepDiver1975** [comment]
> @deepdiver1975 can you help with moving the repo into the ownCloud organisation while keeping the repository name the same?

sure

@Instagit please transfer the repo to my personal account - I can move it forward to the ownCloud orga then.

**Comment by Instagit** [comment]
Done.

**Comment by DeepDiver1975** [comment]
THX

**Comment by jancborchardt** [comment]
@Instagit yeeeah awesome! Really looking forward to have this better video viewer for 9.0! :)

@karlitschek can you add @Instagit to the ownCloud organization then? Also, what else do we need to do to make sure the video viewer is in for 9.0 – change repos, scripts, etc.?

Maybe we should rename the repo https://github.com/owncloud/videojs-sublime to `videos`? (The old app which currently uses the »videos« name was never used, right?) Or `files_videos`.

**Comment by LukasReschke** [comment]
So this will be the default shipped video viewer? If so I'll have to add that at https://github.com/owncloud/core/issues/22287

**Comment by jancborchardt** [comment]
(I sure hope it will be, yes.)

**Comment by DeepDiver1975** [comment]
According to the info.xml the repo name should be files_videojs-sublime - which might not work because of - ....

 https://github.com/owncloud/videojs-sublime/blob/master/appinfo/info.xml#L3

**Comment by karlitschek** [comment]
Hmm. We should standardize on one app ide that is the same as the repo name.
Can we change the id in info.xml to videojs-sublime ?
We should also add an default enabled tag.

**Comment by karlitschek** [comment]
@Instagit You should now get an invitation from github and have full access. Thanks a lot.

**Comment by nickvergessen** [comment]
@karlitschek `videojs-sublime` does not work, because `-` is not allowed in php class names, so this must not be the app id, otherwise the class loader can not work

**Comment by DeepDiver1975** [comment]
there is no single php file in this app - so it will technically work

**Comment by nickvergessen** [comment]
And when it ever needs one it needs to change, then the appconfig values (enabled, version, ...) don't match anymore, etc.

**Comment by DeepDiver1975** [comment]
Very true - we need to have a proper name which fits to the specification - let's open a new pr to discuss this properly
